# Generated by Django 4.2.6 on 2023-12-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sph',
            field=models.IntegerField(),
        ),
    ]
